package com.leetcode.medium.design;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

class SnapshotArray {
    //https://leetcode.com/problems/snapshot-array/
    //1146. Snapshot Array
    //FOREIGN_SOLUTION
    //TOP

    private List<Integer> list = new ArrayList<>();
    private Map<String, Integer> map = new HashMap<>();
    private int length = 0;
    private int snapSize = 0;
    private Map<Integer, Integer> varSnap = new HashMap<>();

    public SnapshotArray(int length) {
        this.length = length;
        for (int i = 0; i < length; i++) {
            list.add(0);
            map.put(snapSize + "" + i, 0);
            varSnap.put(i, snapSize);
        }
    }

    public void set(int index, int val) {
        int prev = varSnap.get(index);
        for (int i = prev + 1; i < snapSize; i++) {
            map.put(i + "" + index, list.get(index));
        }
        varSnap.put(index, snapSize);

        map.put(snapSize + "" + index, val);
        list.set(index, val);
    }

    public int snap() {
        return snapSize++;
    }

    public int get(int index, int snap_id) {
        var n = map.get(snap_id + "" + index);
        if (n != null) return n;
        return 0;
    }
}


class SnapshotArray1 {
    private int snapId = 0;
    private TreeMap<Integer, Integer>[] map;

    public SnapshotArray1(int length) {
        map = new TreeMap[length];
        for (int i = 0; i < length; i++) {
            map[i] = new TreeMap<Integer, Integer>();
            map[i].put(0, 0);
        }
    }

    public void set(int index, int val) {
        map[index].put(snapId, val);
    }

    public int snap() {
        return snapId++;
    }

    public int get(int index, int snap_id) {
        return map[index].floorEntry(snap_id).getValue();
    }
}

public class _1146_Snapshot_Array {

    public static void main(String[] args) {
        SnapshotArray sa = new SnapshotArray(3);
//        sa.set(1, 6);
//        sa.snap();
//        sa.snap();
//        sa.set(1, 19);
//        sa.set(0, 4);
//        sa.get(2, 1);
//        sa.get(2, 0);
//        sa.get(0, 1);

        SnapshotArray s = null;

        for (int i = 0; i < Tests.commands.length; i++) {
            String str = Tests.commands[i];
            int[] arg = Tests.args[i];

            if ("SnapshotArray".equals(str)) {
                s = new SnapshotArray(arg[0]);
            } else if ("snap".equals(str)) {
                s.snap();
            } else if ("get".equals(str)) {
                s.get(arg[0], arg[1]);
            } else {
                s.set(arg[0], arg[1]);
            }
        }
    }
}

class Tests {
  public static String[] commands = {
        "SnapshotArray",
                "snap",
                "get",
                "get",
                "get",
                "snap",
                "snap",
                "set",
                "snap",
                "set",
                "set",
                "get",
                "set",
                "set",
                "snap",
                "get",
                "snap",
                "get",
                "get",
                "get",
                "snap",
                "set",
                "snap",
                "get",
                "set",
                "snap",
                "snap",
                "get",
                "get",
                "snap",
                "set",
                "set",
                "snap",
                "set",
                "get",
                "snap",
                "set",
                "get",
                "get",
                "snap",
                "snap",
                "set",
                "set",
                "get",
                "set",
                "get",
                "snap",
                "snap",
                "get",
                "set",
                "snap",
                "set",
                "set",
                "get",
                "snap",
                "set",
                "get",
                "snap",
                "set",
                "set",
                "get",
                "get",
                "snap",
                "snap",
                "snap",
                "snap",
                "snap",
                "get",
                "get",
                "get",
                "snap",
                "set",
                "get",
                "get",
                "set",
                "get",
                "set",
                "set",
                "snap",
                "set",
                "snap",
                "set",
                "set",
                "set",
                "get",
                "get",
                "get",
                "set",
                "set",
                "snap",
                "get",
                "get",
                "snap",
                "set",
                "get",
                "get",
                "snap",
                "snap",
                "set",
                "snap",
                "set",
                "snap",
                "get",
                "get",
                "snap",
                "snap",
                "get",
                "get",
                "get",
                "set",
                "set",
                "set",
                "snap",
                "snap",
                "set",
                "get",
                "get",
                "set",
                "get",
                "set",
                "snap",
                "get",
                "set",
                "get",
                "get",
                "snap",
                "get",
                "set",
                "set",
                "get",
                "set",
                "set",
                "set",
                "get",
                "get",
                "get",
                "get",
                "get",
                "get",
                "snap",
                "snap",
                "set",
                "set",
                "snap",
                "set",
                "snap",
                "snap",
                "snap",
                "snap",
                "set",
                "get",
                "set",
                "get",
                "get",
                "snap",
                "snap",
                "get",
                "get",
                "snap",
                "set",
                "set",
                "set",
                "get",
                "snap",
                "set",
                "snap",
                "set",
                "set",
                "snap",
                "snap",
                "get",
                "snap",
                "snap",
                "set",
                "set",
                "snap",
                "set",
                "get",
                "set",
                "get",
                "get",
                "snap",
                "snap",
                "get",
                "get",
                "set",
                "snap",
                "snap",
                "set",
                "get",
                "get",
                "set",
                "snap",
                "get",
                "get",
                "set",
                "snap",
                "snap",
                "snap",
                "get",
                "snap",
                "set",
                "snap",
                "get",
                "set",
                "snap",
                "snap",
                "snap",
                "set",
                "snap",
                "get",
                "get",
                "get",
                "set",
                "set",
                "set",
                "get",
                "snap",
                "snap",
                "get",
                "snap",
                "get",
                "snap",
                "snap",
                "set",
                "set",
                "snap",
                "snap",
                "snap",
                "get",
                "get",
                "snap",
                "snap",
                "set",
                "snap",
                "snap",
                "set",
                "snap",
                "snap",
                "snap",
                "set",
                "get",
                "set",
                "get",
                "snap",
                "get",
                "snap",
                "snap",
                "snap",
                "snap",
                "snap",
                "snap",
                "get",
                "get",
                "snap",
                "snap",
                "snap",
                "snap",
                "get",
                "get",
                "snap",
                "get",
                "get",
                "get",
                "snap",
                "set",
                "get",
                "set",
                "get",
                "set",
                "get",
                "get",
                "get",
                "snap",
                "snap",
                "set",
                "snap",
                "snap",
                "get",
                "set",
                "get",
                "get",
                "snap",
                "snap",
                "get",
                "set",
                "get",
                "get",
                "set",
                "get",
                "get",
                "snap",
                "set",
                "set",
                "set",
                "set",
                "get",
                "get",
                "get",
                "get",
                "get",
                "set",
                "snap",
                "set",
                "snap",
                "get",
                "set",
                "get",
                "set",
                "snap",
                "get",
                "snap",
                "set",
                "get",
                "snap",
                "set",
                "snap",
                "get",
                "set",
                "set",
                "snap",
                "snap",
                "snap",
                "snap",
                "set",
                "snap",
                "get",
                "get",
                "get",
                "snap",
                "snap",
                "get",
                "get",
                "snap",
                "get",
                "snap",
                "get",
                "set",
                "get",
                "set",
                "set",
                "set",
                "set",
                "get",
                "snap",
                "set",
                "set",
                "snap",
                "snap",
                "set",
                "snap",
                "get",
                "get",
                "get",
                "snap",
                "snap",
                "get",
                "get",
                "set",
                "set",
                "get",
                "get",
                "snap",
                "set",
                "snap",
                "snap",
                "set",
                "get",
                "get",
                "set",
                "get",
                "get",
                "set",
                "get",
                "set",
                "snap",
                "get",
                "snap",
                "get",
                "snap",
                "snap",
                "get",
                "get",
                "snap",
                "set",
                "snap",
                "snap",
                "snap",
                "get",
                "snap",
                "snap",
                "get",
                "get",
                "set",
                "snap",
                "get",
                "snap",
                "snap",
                "snap",
                "set",
                "snap",
                "set",
                "snap",
                "set",
                "snap",
                "snap",
                "snap",
                "snap",
                "set",
                "snap",
                "set",
                "snap",
                "snap",
                "set",
                "get",
                "snap",
                "set",
                "set",
                "set",
                "set",
                "set",
                "set",
                "snap",
                "set",
                "set",
                "snap",
                "get",
                "get",
                "get",
                "get",
                "snap",
                "get",
                "get",
                "set",
                "get",
                "set",
                "set",
                "set",
                "set",
                "set",
                "get",
                "set",
                "snap",
                "get",
                "set",
                "snap",
                "get",
                "get",
                "set",
                "get",
                "get",
                "set",
                "snap",
                "set",
                "snap",
                "snap",
                "set",
                "snap",
                "snap",
                "set",
                "snap",
                "set",
                "set",
                "get",
                "get",
                "snap",
                "get",
                "snap",
                "snap",
                "get",
                "snap",
                "get",
                "snap",
                "get",
                "snap",
                "set",
                "snap",
                "snap",
                "get",
                "get",
                "set",
                "get",
                "set",
                "snap",
                "snap",
                "snap",
                "set",
                "snap",
                "get",
                "get",
                "get",
                "get",
                "set",
                "snap",
                "get",
                "snap",
                "snap",
                "snap",
                "snap",
                "get",
                "get",
                "snap",
                "snap",
                "set",
                "snap",
                "set",
                "get",
                "get",
                "get",
                "get",
                "snap",
                "set",
                "get",
                "snap",
                "snap",
                "snap",
                "snap",
                "set",
                "get",
                "snap",
                "snap",
                "snap",
                "get",
                "set",
                "set",
                "set",
                "set",
                "snap",
                "snap",
                "get",
                "set",
                "snap",
                "snap",
                "get",
                "set",
                "snap",
                "snap",
                "set",
                "set",
                "snap",
                "snap",
                "set",
                "set",
                "snap",
                "get",
                "snap",
                "set",
                "snap",
                "snap",
                "snap",
                "snap",
                "snap",
                "snap",
                "set",
                "set",
                "get",
                "snap",
                "set",
                "snap",
                "get",
                "snap",
                "get",
                "snap",
                "set",
                "set",
                "snap",
                "set",
                "set",
                "get",
                "snap",
                "get",
                "snap",
                "get",
                "snap",
                "get",
                "snap",
                "snap",
                "set",
                "get",
                "get",
                "set",
                "get",
                "snap",
                "set",
                "set",
                "get",
                "get",
                "snap",
                "set",
                "snap",
                "get",
                "snap",
                "get",
                "snap",
                "get",
                "snap",
                "set",
                "get",
                "set",
                "get",
                "snap",
                "set",
                "set",
                "set",
                "set",
                "get",
                "snap",
                "get",
                "set",
                "get",
                "snap",
                "snap",
                "set",
                "set",
                "set",
                "snap",
                "set",
                "snap",
                "get",
                "set",
                "snap",
                "set",
                "snap",
                "set",
                "get",
                "snap",
                "snap",
                "set",
                "set",
                "set",
                "get",
                "get",
                "get",
                "set",
                "get",
                "set",
                "get",
                "set",
                "set",
                "snap",
                "get",
                "set",
                "snap",
                "get",
                "get",
                "snap",
                "get",
                "set",
                "get",
                "get",
                "get",
                "snap",
                "get",
                "set",
                "get",
                "get",
                "get",
                "get",
                "snap",
                "get",
                "set",
                "snap",
                "set",
                "snap",
                "snap",
                "snap",
                "snap",
                "set",
                "snap",
                "snap",
                "snap",
                "get",
                "snap",
                "get",
                "get",
                "set",
                "set",
                "get",
                "snap",
                "set",
                "set",
                "get",
                "get",
                "get",
                "set",
                "set",
                "get",
                "snap",
                "snap",
                "snap",
                "snap",
                "get",
                "set",
                "snap",
                "set",
                "snap",
                "snap",
                "set",
                "set",
                "get",
                "get",
                "get",
                "snap",
                "snap",
                "set",
                "set",
                "set",
                "set",
                "set",
                "get",
                "get",
                "get",
                "get",
                "set",
                "set",
                "get",
                "set",
                "set",
                "set",
                "set",
                "get",
                "snap",
                "set",
                "set",
                "get",
                "get",
                "set",
                "set",
                "get",
                "get",
                "set",
                "set",
                "set",
                "set",
                "set",
                "set",
                "get",
                "set",
                "set",
                "set",
                "set",
                "get",
                "get",
                "snap",
                "set",
                "set",
                "set",
                "get",
                "snap",
                "snap",
                "set",
                "set",
                "get",
                "snap",
                "snap",
                "snap",
                "get",
                "set",
                "get",
                "get",
                "snap",
                "snap",
                "snap",
                "get",
                "set",
                "snap",
                "snap",
                "set",
                "get",
                "snap",
                "snap",
                "set",
                "snap",
                "set",
                "snap",
                "set",
                "set",
                "snap",
                "snap",
                "get",
                "set",
                "get",
                "get",
                "set",
                "set",
                "get",
                "set",
                "get",
                "set",
                "get",
                "snap",
                "set",
                "set",
                "get",
                "snap",
                "set",
                "snap",
                "snap",
                "get",
                "get",
                "set",
                "snap",
                "snap",
                "snap",
                "set",
                "set",
                "set",
                "get",
                "get",
                "snap",
                "snap",
                "set",
                "snap",
                "snap",
                "get",
                "get",
                "snap",
                "set",
                "snap",
                "get",
                "get",
                "set",
                "get",
                "set",
                "set",
                "snap",
                "get",
                "set",
                "set",
                "set",
                "set",
                "set",
                "set",
                "snap",
                "snap",
                "get",
                "set",
                "snap",
                "snap",
                "set",
                "snap",
                "snap",
                "set",
                "get",
                "set",
                "snap",
                "snap",
                "get",
                "get",
                "set",
                "snap",
                "set",
                "set",
                "get",
                "get",
                "snap",
                "snap",
                "snap",
                "get",
                "set",
                "snap",
                "get",
                "snap",
                "get",
                "get",
                "get",
                "get",
                "snap",
                "get",
                "set",
                "get",
                "get",
                "set",
                "snap",
                "get",
                "set",
                "get",
                "set",
                "get",
                "set",
                "set",
                "get",
                "set",
                "snap",
                "snap",
                "snap",
                "get",
                "get",
                "snap",
                "snap",
                "snap",
                "get",
                "snap",
                "snap",
                "get",
                "snap",
                "set",
                "snap",
                "set",
                "snap",
                "snap",
                "get",
                "set",
                "snap",
                "get",
                "set",
                "get",
                "snap",
                "set",
                "set",
                "get",
                "set",
                "set",
                "set",
                "get",
                "set",
                "get",
                "get",
                "get",
                "get",
                "snap",
                "get",
                "set",
                "snap",
                "set",
                "snap",
                "snap",
                "set",
                "snap",
                "snap",
                "snap",
                "snap",
                "snap",
                "snap",
                "set",
                "snap",
                "set",
                "snap",
                "set",
                "get",
                "snap",
                "snap",
                "get",
                "set",
                "get",
                "set",
                "snap",
                "set",
                "set",
                "snap",
                "get",
                "snap",
                "get",
                "set",
                "get",
                "get",
                "get",
                "set",
                "set",
                "snap",
                "set",
                "get",
                "snap",
                "get",
                "set",
                "snap",
                "snap",
                "snap",
                "set",
                "set",
                "set",
                "set",
                "set",
                "snap",
                "get",
                "snap",
                "snap",
                "get",
                "get",
                "get",
                "set",
                "snap",
                "set",
                "set",
                "snap",
                "snap",
                "set",
                "snap",
                "set",
                "set",
                "set",
                "set",
                "snap",
                "get",
                "get",
                "snap",
                "set",
                "set",
                "snap",
                "snap",
                "snap"
    };
    public static int[][] args = {
        {
            100
        },
        {

        },
        {
            50,
                    0
        },
        {
            35,
                    0
        },
        {
            78,
                    0
        },
        {

        },
        {

        },
        {
            74,
                    179820995
        },
        {

        },
        {
            51,
                    591818187
        },
        {
            75,
                    884797082
        },
        {
            3,
                    0
        },
        {
            29,
                    923200623
        },
        {
            51,
                    276890797
        },
        {

        },
        {
            94,
                    2
        },
        {

        },
        {
            47,
                    1
        },
        {
            40,
                    4
        },
        {
            93,
                    1
        },
        {

        },
        {
            66,
                    539693765
        },
        {

        },
        {
            62,
                    4
        },
        {
            45,
                    464332702
        },
        {

        },
        {

        },
        {
            10,
                    8
        },
        {
            15,
                    5
        },
        {

        },
        {
            37,
                    615208237
        },
        {
            9,
                    248887329
        },
        {

        },
        {
            18,
                    49542080
        },
        {
            62,
                    7
        },
        {

        },
        {
            76,
                    33929822
        },
        {
            40,
                    2
        },
        {
            66,
                    11
        },
        {

        },
        {

        },
        {
            91,
                    643494983
        },
        {
            43,
                    33324704
        },
        {
            22,
                    7
        },
        {
            55,
                    338405759
        },
        {
            58,
                    10
        },
        {

        },
        {

        },
        {
            82,
                    0
        },
        {
            83,
                    714187040
        },
        {

        },
        {
            85,
                    17453914
        },
        {
            0,
                    502844009
        },
        {
            12,
                    2
        },
        {

        },
        {
            29,
                    281035593
        },
        {
            66,
                    3
        },
        {

        },
        {
            20,
                    687289044
        },
        {
            85,
                    266123117
        },
        {
            70,
                    1
        },
        {
            27,
                    3
        },
        {

        },
        {

        },
        {

        },
        {

        },
        {

        },
        {
            22,
                    3
        },
        {
            83,
                    9
        },
        {
            76,
                    11
        },
        {

        },
        {
            60,
                    284773089
        },
        {
            18,
                    0
        },
        {
            82,
                    0
        },
        {
            85,
                    766603386
        },
        {
            71,
                    11
        },
        {
            53,
                    612338013
        },
        {
            45,
                    472336403
        },
        {

        },
        {
            71,
                    901350385
        },
        {

        },
        {
            16,
                    191371378
        },
        {
            40,
                    55688771
        },
        {
            24,
                    805321444
        },
        {
            2,
                    23
        },
        {
            8,
                    23
        },
        {
            96,
                    18
        },
        {
            89,
                    311550974
        },
        {
            16,
                    590038876
        },
        {

        },
        {
            98,
                    19
        },
        {
            66,
                    21
        },
        {

        },
        {
            98,
                    439498831
        },
        {
            15,
                    2
        },
        {
            87,
                    2
        },
        {

        },
        {

        },
        {
            84,
                    244017095
        },
        {

        },
        {
            75,
                    470026554
        },
        {

        },
        {
            12,
                    31
        },
        {
            75,
                    24
        },
        {

        },
        {

        },
        {
            48,
                    1
        },
        {
            52,
                    5
        },
        {
            15,
                    13
        },
        {
            18,
                    182195167
        },
        {
            0,
                    358416754
        },
        {
            99,
                    597414548
        },
        {

        },
        {

        },
        {
            26,
                    300124271
        },
        {
            0,
                    8
        },
        {
            70,
                    23
        },
        {
            98,
                    885773728
        },
        {
            11,
                    0
        },
        {
            38,
                    884438668
        },
        {

        },
        {
            19,
                    3
        },
        {
            17,
                    55016891
        },
        {
            99,
                    6
        },
        {
            11,
                    34
        },
        {

        },
        {
            97,
                    4
        },
        {
            34,
                    362145390
        },
        {
            22,
                    200719334
        },
        {
            47,
                    34
        },
        {
            12,
                    874492133
        },
        {
            41,
                    567691477
        },
        {
            51,
                    990048311
        },
        {
            24,
                    30
        },
        {
            56,
                    35
        },
        {
            39,
                    37
        },
        {
            58,
                    11
        },
        {
            4,
                    6
        },
        {
            24,
                    18
        },
        {

        },
        {

        },
        {
            60,
                    788108772
        },
        {
            56,
                    990758846
        },
        {

        },
        {
            90,
                    114556686
        },
        {

        },
        {

        },
        {

        },
        {

        },
        {
            42,
                    380189426
        },
        {
            7,
                    15
        },
        {
            90,
                    133844371
        },
        {
            14,
                    34
        },
        {
            77,
                    31
        },
        {

        },
        {

        },
        {
            56,
                    40
        },
        {
            29,
                    23
        },
        {

        },
        {
            1,
                    708871437
        },
        {
            44,
                    262629344
        },
        {
            54,
                    717214218
        },
        {
            80,
                    18
        },
        {

        },
        {
            88,
                    301669669
        },
        {

        },
        {
            33,
                    701937397
        },
        {
            86,
                    229863649
        },
        {

        },
        {

        },
        {
            74,
                    23
        },
        {

        },
        {

        },
        {
            72,
                    70257309
        },
        {
            6,
                    749455331
        },
        {

        },
        {
            5,
                    173212713
        },
        {
            21,
                    15
        },
        {
            75,
                    887011459
        },
        {
            82,
                    11
        },
        {
            43,
                    35
        },
        {

        },
        {

        },
        {
            18,
                    28
        },
        {
            30,
                    34
        },
        {
            55,
                    47234033
        },
        {

        },
        {

        },
        {
            10,
                    839630129
        },
        {
            60,
                    9
        },
        {
            23,
                    9
        },
        {
            54,
                    161322048
        },
        {

        },
        {
            13,
                    37
        },
        {
            57,
                    3
        },
        {
            0,
                    993977492
        },
        {

        },
        {

        },
        {

        },
        {
            10,
                    31
        },
        {

        },
        {
            73,
                    535927553
        },
        {

        },
        {
            0,
                    20
        },
        {
            45,
                    924316559
        },
        {

        },
        {

        },
        {

        },
        {
            96,
                    375322759
        },
        {

        },
        {
            11,
                    2
        },
        {
            95,
                    19
        },
        {
            52,
                    11
        },
        {
            93,
                    693747822
        },
        {
            96,
                    88182172
        },
        {
            2,
                    902668813
        },
        {
            68,
                    58
        },
        {

        },
        {

        },
        {
            12,
                    48
        },
        {

        },
        {
            61,
                    12
        },
        {

        },
        {

        },
        {
            89,
                    908201805
        },
        {
            2,
                    378523443
        },
        {

        },
        {

        },
        {

        },
        {
            92,
                    77
        },
        {
            62,
                    71
        },
        {

        },
        {

        },
        {
            10,
                    112582852
        },
        {

        },
        {

        },
        {
            51,
                    505946865
        },
        {

        },
        {

        },
        {

        },
        {
            92,
                    704200533
        },
        {
            14,
                    76
        },
        {
            33,
                    330844936
        },
        {
            74,
                    9
        },
        {

        },
        {
            57,
                    55
        },
        {

        },
        {

        },
        {

        },
        {

        },
        {

        },
        {

        },
        {
            75,
                    10
        },
        {
            96,
                    76
        },
        {

        },
        {

        },
        {

        },
        {

        },
        {
            0,
                    94
        },
        {
            47,
                    61
        },
        {

        },
        {
            27,
                    72
        },
        {
            33,
                    25
        },
        {
            31,
                    57
        },
        {

        },
        {
            35,
                    758847353
        },
        {
            9,
                    51
        },
        {
            89,
                    68987168
        },
        {
            8,
                    11
        },
        {
            7,
                    595528447
        },
        {
            22,
                    60
        },
        {
            30,
                    37
        },
        {
            98,
                    69
        },
        {

        },
        {

        },
        {
            58,
                    743171675
        },
        {

        },
        {

        },
        {
            32,
                    70
        },
        {
            70,
                    356306884
        },
        {
            5,
                    0
        },
        {
            2,
                    89
        },
        {

        },
        {

        },
        {
            33,
                    91
        },
        {
            80,
                    956361292
        },
        {
            50,
                    95
        },
        {
            94,
                    102
        },
        {
            84,
                    213138414
        },
        {
            15,
                    7
        },
        {
            13,
                    19
        },
        {

        },
        {
            60,
                    324479205
        },
        {
            7,
                    145808098
        },
        {
            19,
                    517522040
        },
        {
            98,
                    878437107
        },
        {
            19,
                    52
        },
        {
            99,
                    101
        },
        {
            94,
                    95
        },
        {
            70,
                    81
        },
        {
            44,
                    75
        },
        {
            32,
                    602108117
        },
        {

        },
        {
            22,
                    917245660
        },
        {

        },
        {
            86,
                    102
        },
        {
            27,
                    51171362
        },
        {
            10,
                    35
        },
        {
            89,
                    668497884
        },
        {

        },
        {
            11,
                    55
        },
        {

        },
        {
            25,
                    1315376
        },
        {
            59,
                    106
        },
        {

        },
        {
            8,
                    3587541
        },
        {

        },
        {
            94,
                    79
        },
        {
            2,
                    168339134
        },
        {
            57,
                    611254436
        },
        {

        },
        {

        },
        {

        },
        {

        },
        {
            73,
                    906839262
        },
        {

        },
        {
            97,
                    84
        },
        {
            19,
                    17
        },
        {
            35,
                    112
        },
        {

        },
        {

        },
        {
            4,
                    117
        },
        {
            41,
                    25
        },
        {

        },
        {
            86,
                    35
        },
        {

        },
        {
            54,
                    70
        },
        {
            2,
                    419146691
        },
        {
            48,
                    31
        },
        {
            97,
                    591156511
        },
        {
            3,
                    575337908
        },
        {
            70,
                    555610130
        },
        {
            21,
                    245761553
        },
        {
            30,
                    101
        },
        {

        },
        {
            45,
                    761771675
        },
        {
            17,
                    788607922
        },
        {

        },
        {

        },
        {
            16,
                    712018524
        },
        {

        },
        {
            56,
                    123
        },
        {
            84,
                    95
        },
        {
            89,
                    96
        },
        {

        },
        {

        },
        {
            71,
                    53
        },
        {
            42,
                    75
        },
        {
            40,
                    637086517
        },
        {
            7,
                    819459609
        },
        {
            66,
                    96
        },
        {
            23,
                    79
        },
        {

        },
        {
            98,
                    158186979
        },
        {

        },
        {

        },
        {
            2,
                    415430671
        },
        {
            50,
                    8
        },
        {
            80,
                    73
        },
        {
            13,
                    803748586
        },
        {
            68,
                    90
        },
        {
            91,
                    95
        },
        {
            22,
                    734076467
        },
        {
            83,
                    98
        },
        {
            26,
                    230787932
        },
        {

        },
        {
            48,
                    122
        },
        {

        },
        {
            92,
                    120
        },
        {

        },
        {

        },
        {
            79,
                    5
        },
        {
            45,
                    46
        },
        {

        },
        {
            0,
                    462990933
        },
        {

        },
        {

        },
        {

        },
        {
            22,
                    13
        },
        {

        },
        {

        },
        {
            10,
                    41
        },
        {
            30,
                    3
        },
        {
            87,
                    873093194
        },
        {

        },
        {
            80,
                    64
        },
        {

        },
        {

        },
        {

        },
        {
            53,
                    772542261
        },
        {

        },
        {
            26,
                    39547262
        },
        {

        },
        {
            64,
                    363629302
        },
        {

        },
        {

        },
        {

        },
        {

        },
        {
            37,
                    475025506
        },
        {

        },
        {
            95,
                    405252695
        },
        {

        },
        {

        },
        {
            26,
                    517018182
        },
        {
            80,
                    1
        },
        {

        },
        {
            16,
                    113939587
        },
        {
            45,
                    688255105
        },
        {
            89,
                    703758590
        },
        {
            26,
                    954691204
        },
        {
            31,
                    222179242
        },
        {
            52,
                    76861771
        },
        {

        },
        {
            85,
                    519959166
        },
        {
            28,
                    837008521
        },
        {

        },
        {
            46,
                    85
        },
        {
            15,
                    20
        },
        {
            97,
                    152
        },
        {
            47,
                    110
        },
        {

        },
        {
            56,
                    61
        },
        {
            11,
                    62
        },
        {
            77,
                    265113795
        },
        {
            11,
                    151
        },
        {
            49,
                    534721837
        },
        {
            92,
                    412106155
        },
        {
            93,
                    864163541
        },
        {
            7,
                    859708129
        },
        {
            53,
                    443101241
        },
        {
            76,
                    66
        },
        {
            38,
                    173483255
        },
        {

        },
        {
            92,
                    80
        },
        {
            31,
                    160877071
        },
        {

        },
        {
            73,
                    68
        },
        {
            70,
                    102
        },
        {
            7,
                    196244584
        },
        {
            47,
                    150
        },
        {
            90,
                    155
        },
        {
            49,
                    630807597
        },
        {

        },
        {
            29,
                    794195842
        },
        {

        },
        {

        },
        {
            17,
                    20921436
        },
        {

        },
        {

        },
        {
            78,
                    973225284
        },
        {

        },
        {
            58,
                    560230834
        },
        {
            33,
                    623241227
        },
        {
            40,
                    112
        },
        {
            26,
                    119
        },
        {

        },
        {
            60,
                    120
        },
        {

        },
        {

        },
        {
            43,
                    50
        },
        {

        },
        {
            72,
                    76
        },
        {

        },
        {
            67,
                    88
        },
        {

        },
        {
            27,
                    703988406
        },
        {

        },
        {

        },
        {
            98,
                    6
        },
        {
            0,
                    86
        },
        {
            74,
                    601275825
        },
        {
            53,
                    20
        },
        {
            74,
                    34942404
        },
        {

        },
        {

        },
        {

        },
        {
            85,
                    113001580
        },
        {

        },
        {
            98,
                    11
        },
        {
            43,
                    40
        },
        {
            99,
                    140
        },
        {
            41,
                    106
        },
        {
            5,
                    194640709
        },
        {

        },
        {
            74,
                    18
        },
        {

        },
        {

        },
        {

        },
        {

        },
        {
            37,
                    36
        },
        {
            19,
                    108
        },
        {

        },
        {

        },
        {
            81,
                    708030822
        },
        {

        },
        {
            96,
                    582748482
        },
        {
            17,
                    86
        },
        {
            9,
                    83
        },
        {
            4,
                    164
        },
        {
            73,
                    176
        },
        {

        },
        {
            89,
                    186341961
        },
        {
            90,
                    160
        },
        {

        },
        {

        },
        {

        },
        {

        },
        {
            91,
                    839073814
        },
        {
            56,
                    155
        },
        {

        },
        {

        },
        {

        },
        {
            71,
                    38
        },
        {
            92,
                    950666824
        },
        {
            84,
                    816032609
        },
        {
            46,
                    172735333
        },
        {
            42,
                    592909366
        },
        {

        },
        {

        },
        {
            69,
                    34
        },
        {
            28,
                    809018049
        },
        {

        },
        {

        },
        {
            83,
                    32
        },
        {
            39,
                    268218746
        },
        {

        },
        {

        },
        {
            15,
                    835530456
        },
        {
            93,
                    244006649
        },
        {

        },
        {

        },
        {
            41,
                    958424971
        },
        {
            35,
                    783329981
        },
        {

        },
        {
            56,
                    187
        },
        {

        },
        {
            33,
                    834016651
        },
        {

        },
        {

        },
        {

        },
        {

        },
        {

        },
        {

        },
        {
            91,
                    172607428
        },
        {
            11,
                    512861703
        },
        {
            98,
                    143
        },
        {

        },
        {
            52,
                    774442145
        },
        {

        },
        {
            11,
                    135
        },
        {

        },
        {
            45,
                    138
        },
        {

        },
        {
            0,
                    166311419
        },
        {
            97,
                    940445990
        },
        {

        },
        {
            6,
                    554696626
        },
        {
            86,
                    627813172
        },
        {
            48,
                    95
        },
        {

        },
        {
            15,
                    116
        },
        {

        },
        {
            40,
                    6
        },
        {

        },
        {
            46,
                    1
        },
        {

        },
        {

        },
        {
            18,
                    194983711
        },
        {
            46,
                    44
        },
        {
            10,
                    198
        },
        {
            19,
                    967140713
        },
        {
            34,
                    95
        },
        {

        },
        {
            55,
                    156672508
        },
        {
            25,
                    50725644
        },
        {
            65,
                    54
        },
        {
            45,
                    155
        },
        {

        },
        {
            76,
                    501636555
        },
        {

        },
        {
            79,
                    193
        },
        {

        },
        {
            4,
                    0
        },
        {

        },
        {
            19,
                    2
        },
        {

        },
        {
            49,
                    546831352
        },
        {
            32,
                    48
        },
        {
            23,
                    54413035
        },
        {
            16,
                    171
        },
        {

        },
        {
            71,
                    434036750
        },
        {
            50,
                    237491868
        },
        {
            50,
                    994993281
        },
        {
            34,
                    333699022
        },
        {
            48,
                    17
        },
        {

        },
        {
            70,
                    43
        },
        {
            75,
                    121298358
        },
        {
            1,
                    226
        },
        {

        },
        {

        },
        {
            14,
                    904962976
        },
        {
            78,
                    474129183
        },
        {
            22,
                    719114208
        },
        {

        },
        {
            58,
                    286451352
        },
        {

        },
        {
            20,
                    65
        },
        {
            85,
                    385853253
        },
        {

        },
        {
            99,
                    471929723
        },
        {

        },
        {
            61,
                    588655056
        },
        {
            22,
                    134
        },
        {

        },
        {

        },
        {
            18,
                    119192007
        },
        {
            21,
                    333799869
        },
        {
            26,
                    696010559
        },
        {
            39,
                    221
        },
        {
            23,
                    23
        },
        {
            0,
                    89
        },
        {
            2,
                    714840215
        },
        {
            64,
                    89
        },
        {
            86,
                    3019617
        },
        {
            81,
                    82
        },
        {
            37,
                    173792569
        },
        {
            65,
                    755840620
        },
        {

        },
        {
            9,
                    174
        },
        {
            12,
                    405503807
        },
        {

        },
        {
            49,
                    202
        },
        {
            82,
                    165
        },
        {

        },
        {
            51,
                    15
        },
        {
            1,
                    548503809
        },
        {
            45,
                    32
        },
        {
            15,
                    95
        },
        {
            38,
                    16
        },
        {

        },
        {
            94,
                    217
        },
        {
            72,
                    802450594
        },
        {
            76,
                    238
        },
        {
            99,
                    87
        },
        {
            82,
                    97
        },
        {
            56,
                    163
        },
        {

        },
        {
            95,
                    128
        },
        {
            13,
                    298647687
        },
        {

        },
        {
            80,
                    516687396
        },
        {

        },
        {

        },
        {

        },
        {

        },
        {
            21,
                    978097830
        },
        {

        },
        {

        },
        {

        },
        {
            29,
                    13
        },
        {

        },
        {
            12,
                    182
        },
        {
            67,
                    214
        },
        {
            93,
                    365489612
        },
        {
            38,
                    282445195
        },
        {
            28,
                    70
        },
        {

        },
        {
            85,
                    120230293
        },
        {
            22,
                    463792866
        },
        {
            52,
                    27
        },
        {
            46,
                    233
        },
        {
            57,
                    39
        },
        {
            94,
                    780025489
        },
        {
            7,
                    317149441
        },
        {
            43,
                    174
        },
        {

        },
        {

        },
        {

        },
        {

        },
        {
            41,
                    241
        },
        {
            26,
                    429814994
        },
        {

        },
        {
            21,
                    49336399
        },
        {

        },
        {

        },
        {
            60,
                    586702863
        },
        {
            55,
                    676460965
        },
        {
            50,
                    123
        },
        {
            94,
                    251
        },
        {
            91,
                    108
        },
        {

        },
        {

        },
        {
            14,
                    147392138
        },
        {
            13,
                    302524733
        },
        {
            68,
                    772987378
        },
        {
            14,
                    929378950
        },
        {
            95,
                    83251284
        },
        {
            93,
                    145
        },
        {
            80,
                    22
        },
        {
            51,
                    173
        },
        {
            19,
                    252
        },
        {
            82,
                    854471045
        },
        {
            63,
                    184849791
        },
        {
            9,
                    145
        },
        {
            95,
                    624208564
        },
        {
            57,
                    423756270
        },
        {
            25,
                    411981367
        },
        {
            27,
                    696493080
        },
        {
            95,
                    21
        },
        {

        },
        {
            57,
                    151886277
        },
        {
            32,
                    643227895
        },
        {
            60,
                    166
        },
        {
            99,
                    9
        },
        {
            75,
                    974185422
        },
        {
            98,
                    820815281
        },
        {
            0,
                    117
        },
        {
            22,
                    245
        },
        {
            91,
                    738510892
        },
        {
            64,
                    518238457
        },
        {
            48,
                    190677182
        },
        {
            77,
                    443609467
        },
        {
            71,
                    133584395
        },
        {
            80,
                    365286353
        },
        {
            56,
                    9
        },
        {
            13,
                    810107922
        },
        {
            23,
                    453300408
        },
        {
            27,
                    77570307
        },
        {
            77,
                    590906042
        },
        {
            85,
                    0
        },
        {
            19,
                    198
        },
        {

        },
        {
            28,
                    698141112
        },
        {
            91,
                    906810152
        },
        {
            21,
                    520192974
        },
        {
            92,
                    44
        },
        {

        },
        {

        },
        {
            63,
                    153133280
        },
        {
            11,
                    275198356
        },
        {
            41,
                    174
        },
        {

        },
        {

        },
        {

        },
        {
            8,
                    193
        },
        {
            85,
                    755986747
        },
        {
            55,
                    206
        },
        {
            53,
                    53
        },
        {

        },
        {

        },
        {

        },
        {
            58,
                    108
        },
        {
            52,
                    684226180
        },
        {

        },
        {

        },
        {
            76,
                    238158976
        },
        {
            87,
                    225
        },
        {

        },
        {

        },
        {
            92,
                    222632552
        },
        {

        },
        {
            42,
                    924673960
        },
        {

        },
        {
            80,
                    69280431
        },
        {
            84,
                    356295414
        },
        {

        },
        {

        },
        {
            28,
                    106
        },
        {
            97,
                    938472413
        },
        {
            12,
                    240
        },
        {
            37,
                    147
        },
        {
            6,
                    64506801
        },
        {
            72,
                    83098105
        },
        {
            11,
                    198
        },
        {
            90,
                    16102368
        },
        {
            8,
                    268
        },
        {
            78,
                    499438647
        },
        {
            96,
                    191
        },
        {

        },
        {
            68,
                    837520995
        },
        {
            12,
                    904109253
        },
        {
            6,
                    128
        },
        {

        },
        {
            58,
                    530428788
        },
        {

        },
        {

        },
        {
            64,
                    173
        },
        {
            61,
                    117
        },
        {
            52,
                    247490319
        },
        {

        },
        {

        },
        {

        },
        {
            9,
                    526791194
        },
        {
            39,
                    337913750
        },
        {
            20,
                    306302953
        },
        {
            27,
                    98
        },
        {
            95,
                    88
        },
        {

        },
        {

        },
        {
            40,
                    519088887
        },
        {

        },
        {

        },
        {
            98,
                    188
        },
        {
            29,
                    62
        },
        {

        },
        {
            73,
                    886727417
        },
        {

        },
        {
            56,
                    133
        },
        {
            55,
                    144
        },
        {
            15,
                    180162802
        },
        {
            83,
                    89
        },
        {
            4,
                    653679276
        },
        {
            29,
                    610632035
        },
        {

        },
        {
            87,
                    175
        },
        {
            87,
                    165742209
        },
        {
            62,
                    984611683
        },
        {
            37,
                    706360902
        },
        {
            50,
                    992175680
        },
        {
            80,
                    403043531
        },
        {
            38,
                    141927252
        },
        {

        },
        {

        },
        {
            56,
                    268
        },
        {
            58,
                    841245242
        },
        {

        },
        {

        },
        {
            2,
                    890677283
        },
        {

        },
        {

        },
        {
            13,
                    378127239
        },
        {
            4,
                    175
        },
        {
            69,
                    934897645
        },
        {

        },
        {

        },
        {
            82,
                    91
        },
        {
            46,
                    13
        },
        {
            42,
                    39769604
        },
        {

        },
        {
            79,
                    325559652
        },
        {
            82,
                    132477967
        },
        {
            69,
                    260
        },
        {
            47,
                    113
        },
        {

        },
        {

        },
        {

        },
        {
            67,
                    128
        },
        {
            37,
                    383897099
        },
        {

        },
        {
            67,
                    97
        },
        {

        },
        {
            49,
                    35
        },
        {
            46,
                    193
        },
        {
            94,
                    291
        },
        {
            79,
                    262
        },
        {

        },
        {
            81,
                    171
        },
        {
            96,
                    558720180
        },
        {
            29,
                    86
        },
        {
            20,
                    261
        },
        {
            17,
                    615033508
        },
        {

        },
        {
            62,
                    159
        },
        {
            23,
                    449206997
        },
        {
            48,
                    262
        },
        {
            87,
                    827219794
        },
        {
            58,
                    221
        },
        {
            59,
                    469696428
        },
        {
            74,
                    980426911
        },
        {
            74,
                    251
        },
        {
            65,
                    330348480
        },
        {

        },
        {

        },
        {

        },
        {
            17,
                    299
        },
        {
            93,
                    98
        },
        {

        },
        {

        },
        {

        },
        {
            82,
                    184
        },
        {

        },
        {

        },
        {
            66,
                    136
        },
        {

        },
        {
            17,
                    185739418
        },
        {

        },
        {
            37,
                    557868106
        },
        {

        },
        {

        },
        {
            4,
                    129
        },
        {
            98,
                    77072899
        },
        {

        },
        {
            15,
                    276
        },
        {
            27,
                    67669072
        },
        {
            49,
                    183
        },
        {

        },
        {
            31,
                    73789707
        },
        {
            67,
                    53473241
        },
        {
            80,
                    36
        },
        {
            46,
                    83142367
        },
        {
            17,
                    642292364
        },
        {
            67,
                    583252240
        },
        {
            18,
                    9
        },
        {
            62,
                    611403497
        },
        {
            40,
                    168
        },
        {
            92,
                    84
        },
        {
            58,
                    313
        },
        {
            6,
                    165
        },
        {

        },
        {
            52,
                    252
        },
        {
            36,
                    486524375
        },
        {

        },
        {
            90,
                    844365837
        },
        {

        },
        {

        },
        {
            70,
                    239721556
        },
        {

        },
        {

        },
        {

        },
        {

        },
        {

        },
        {

        },
        {
            17,
                    451372543
        },
        {

        },
        {
            65,
                    235212130
        },
        {

        },
        {
            33,
                    279473233
        },
        {
            16,
                    251
        },
        {

        },
        {

        },
        {
            28,
                    97
        },
        {
            27,
                    513780506
        },
        {
            69,
                    123
        },
        {
            36,
                    733727622
        },
        {

        },
        {
            80,
                    186876755
        },
        {
            67,
                    574145276
        },
        {

        },
        {
            72,
                    247
        },
        {

        },
        {
            80,
                    43
        },
        {
            96,
                    59694111
        },
        {
            48,
                    60
        },
        {
            50,
                    137
        },
        {
            97,
                    19
        },
        {
            90,
                    746401982
        },
        {
            47,
                    89045212
        },
        {

        },
        {
            46,
                    574180106
        },
        {
            5,
                    314
        },
        {

        },
        {
            8,
                    174
        },
        {
            27,
                    22016677
        },
        {

        },
        {

        },
        {

        },
        {
            87,
                    700396298
        },
        {
            87,
                    357047492
        },
        {
            8,
                    6749088
        },
        {
            48,
                    939135653
        },
        {
            64,
                    33009732
        },
        {

        },
        {
            91,
                    342
        },
        {

        },
        {

        },
        {
            31,
                    87
        },
        {
            24,
                    262
        },
        {
            98,
                    119
        },
        {
            17,
                    494546640
        },
        {

        },
        {
            98,
                    874556316
        },
        {
            79,
                    134296633
        },
        {

        },
        {

        },
        {
            19,
                    422572346
        },
        {

        },
        {
            86,
                    645805142
        },
        {
            10,
                    217552224
        },
        {
            3,
                    310261137
        },
        {
            4,
                    306435046
        },
        {

        },
        {
            36,
                    325
        },
        {
            96,
                    172
        },
        {

        },
        {
            77,
                    767611053
        },
        {
            44,
                    715725169
        },
        {

        },
        {

        },
        {

        }
    };
}
